# Generated by Django 3.1.4 on 2020-12-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(blank=True, max_length=300)),
                ('role', models.CharField(default='customer', max_length=10)),
            ],
        ),
    ]
