# Generated by Django 3.1.4 on 2020-12-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'customer'), ('agent', 'agent')], default='customer', max_length=10),
        ),
    ]
