# Generated by Django 3.1.4 on 2020-12-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
