# Generated by Django 3.1.4 on 2020-12-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20201209_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
