# Generated by Django 3.1.4 on 2020-12-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_auto_20201209_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('principal_amount', models.IntegerField(default=0)),
                ('interest_rate', models.FloatField(default=0.0)),
                ('tenure_months', models.IntegerField(default=0)),
                ('emi', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('rejected', 'rejected'), ('approved', 'approved')], default='new', max_length=10)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='lms.user')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='lms.user')),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='lms.user')),
            ],
        ),
    ]
